[tool.poetry]
name = "jinja2xlsx"
version = "0.1.0"
description = "Convert jinja2-html to xlsx"
authors = ["potykion <potykion@gmail.com>"]
license = "mit"

[tool.poetry.dependencies]
python = "^3.7"
requests-html = "^0.10.0"
openpyxl = "^2.6"
jinja2 = "^2.10"

[tool.poetry.dev-dependencies]
pytest = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
